import { cn } from '@/lib/utils';

export type TruthLabelVariant =
  | 'real_org_data'
  | 'sample_data'
  | 'ai_generated'
  | 'heuristic'
  | 'requires_validation';

const VARIANTS: Record<
  TruthLabelVariant,
  { label: string; dotClass: string; bgClass: string; textClass: string; tooltip: string }
> = {
  real_org_data: {
    label: 'Real org data',
    dotClass: 'bg-truth-real',
    bgClass: 'bg-truth-real/10',
    textClass: 'text-truth-real',
    tooltip: 'Sourced directly from the connected Salesforce org.',
  },
  sample_data: {
    label: 'Sample data',
    dotClass: 'bg-truth-sample',
    bgClass: 'bg-truth-sample/10',
    textClass: 'text-truth-sample',
    tooltip: 'Demo payload — not from a real customer org.',
  },
  ai_generated: {
    label: 'AI-generated draft',
    dotClass: 'bg-truth-ai',
    bgClass: 'bg-truth-ai/10',
    textClass: 'text-truth-ai',
    tooltip: 'Generated by an LLM. Review before use.',
  },
  heuristic: {
    label: 'Heuristic estimate',
    dotClass: 'bg-truth-heuristic',
    bgClass: 'bg-truth-heuristic/15',
    textClass: 'text-truth-heuristic',
    tooltip: 'Calculated from heuristics, not measured directly.',
  },
  requires_validation: {
    label: 'Requires human validation',
    dotClass: 'bg-truth-review',
    bgClass: 'bg-truth-review/15',
    textClass: 'text-truth-review',
    tooltip: 'Flagged for human review before being treated as authoritative.',
  },
};

type Props = {
  variant: TruthLabelVariant;
  className?: string;
  /** Optional override of the visible label (variant default still drives styling). */
  label?: string;
};

export function TruthLabel({ variant, className, label }: Props) {
  const v = VARIANTS[variant];
  return (
    <span
      title={v.tooltip}
      className={cn(
        'inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-xs font-medium',
        v.bgClass,
        v.textClass,
        className,
      )}
    >
      <span className={cn('h-1.5 w-1.5 rounded-full', v.dotClass)} aria-hidden />
      {label ?? v.label}
    </span>
  );
}

export const TRUTH_VARIANTS: TruthLabelVariant[] = [
  'real_org_data',
  'sample_data',
  'ai_generated',
  'heuristic',
  'requires_validation',
];
